### ISSUE TITLE
ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by brettvanderwerff** [mammuth/play-books-notes#13]
Something broke for me with the changes that were made in the repo since yesterday, I now get this error after pulling the new changes

This site can’t be reached
The webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

Does it need to be run in a docker container now or something? 

EDIT: I see the new deployment instruction now, I am guessing docker is required?

**Comment by mammuth** [comment]
Does not need to be run via docker for development, but can.
You can try accessing it via 127.0.0.1:8080. Also note that I moved the app in its own directory. 

I just checked it, running `pipenv run python app.py` from within the `app` directory still works for me👍

**Comment by brettvanderwerff** [comment]
You could probably close this then 127.0.0.1:8080 seems like it is going to right place, but I'm still getting exceptions so it is probably something on my end with authentication. I'm at work right now and can't look too deep. I'll try tonight. Thanks sorry to bug.

**Comment by mammuth** [comment]
Btw, you can reset the oauth state with the endpoints `/revoke` and `/clear`, maybe that's helpful.

**Comment by brettvanderwerff** [comment]
`/clear` endpoint did it, everything works great on my end again thanks.
