### ISSUE TITLE
Error pops up if you dont have a folder for play books notes on your google drive

### ISSUE THREAD

**Issue by brettvanderwerff** [mammuth/play-books-notes#7]
I got your app up and running, but before I actually downloaded playbooks and saved quotes (which generated the folder "Play Books Notes" on my google drive), I was getting an error:

UnboundLocalError: local variable 'notes_folder_id' referenced before assignment.

The error went away after installing play books, saving quotes, and syncing to my google drive. I didn't lose too much time on it, luckily saving quotes was the first thing I tried to fix it, but just a heads up that a more informative printout when this exception pops up might help people. Or a comment in the readme that you must have some quotes saved in your play books and your play books synced to your drive for this to work. Maybe its obvious to other people and its just me that tripped over this. Really nice app you have here I am poking around to see if I can contribute. I have some flask experience, but overall am pretty new to programming.

**Comment by mammuth** [comment]
Yep, at the current stage, there is almost no error handling anywhere :wink: :construction_worker:

I just tinkered around with it yesterday and published it in case it might already be useful for someone else. 

The check whether the folder exists should be easy to implement, go for it if you're interested!

**Comment by brettvanderwerff** [comment]
Ill take a crack at this, I am super new to programming though and don't really know front end too well, so feel free to ignore any changes I propose if they are silly.
